/* Visit sll-base.acs for information */

int oldz;

function void ScaleVelocity(int TID, int scale)
{
	int velx = FixedMul(scale, GetActorVelX(TID));
	int vely = FixedMul(scale, GetActorVelY(TID));
	int velz = FixedMul(scale, GetActorVelZ(TID));
	SetActorVelocity(TID, velx, vely, velz, false, false);
}

function str DoubleDigitSeconds(int seconds)
{
	if (StrLen(StrParam(d:seconds % 60)) < 2) {
		return StrParam(s:"0", d:seconds % 60);
	}
	return StrParam(d:seconds % 60);
}