class ShadowAbilities : LockLoadWeapon
{
	Default
	{
		Weapon.SelectionOrder 3700;
		Weapon.Kickback 9999999999999;
		Weapon.BobRangeX 0.0;
		Weapon.BobRangeY 0.0;
		Weapon.AmmoType "ChaosEnergy";
		Tag "Shadow the Hedgehog";
		+WEAPON.MELEEWEAPON
		+WEAPON.NOAUTOFIRE
	}
	States
	{
		Ready:
			TNT1 A 1 A_WeaponReady();
			Loop;
		Deselect:
			#### # 1 A_Lower(12);
			Loop;
		Select:
			TNT1 A 1 A_Raise(12);
			Loop;
		Fire:
			TNT1 A 0 A_PlaySound("sweapons/swordswing", 1);
			DPNR ABC 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			DPNR D 2 A_CustomPunch(random(1,64)*15, true, CPF_NOTURN, "ShadowMeleeAtk", 95, 0, 0, "ArmorBonus", "sweapons/finalhit");
			DPNR CBA 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			TNT1 AA 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			Goto Ready;
		AltFire:
			TNT1 A 0 A_JumpIf(CountInv("ChaosEnergy") < 2, "Ready");
			SARM ABC 1;
			SARM D 1 {
				A_PlaySound("sweapons/chaosspear", CHAN_WEAPON);
				if (CountInv("PowerSuper")) {
					A_FireProjectile("ChaosSpearEX");
					A_FireProjectile("ChaosSpearEX", -5);
					A_FireProjectile("ChaosSpearEX", 5);
				}
				else {
					A_FireProjectile("ChaosSpear");
					A_TakeInventory("ChaosEnergy", 2);
				}
			}
			SARM DDDDCBA 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			TNT1 A 5;
			Goto Ready;
		Spawn:
			SHAD A -1;
			Stop;
	}
}

class HighShovel : LockLoadWeapon
{
	Default
	{
		Weapon.SelectionOrder 1400;
		Weapon.KickBack 1500;
		Tag "High Shovel";
		Inventory.PickupMessage "\c[ShadowRedBlack]High shovel!";
		+WEAPON.MELEEWEAPON
		+WEAPON.NOAUTOFIRE
	}
	States
	{
		Ready:
			SHOV A 1 A_WeaponReady();
			Loop;
		Deselect:
			#### # 1 A_Lower(12);
			Loop;
		Select:
			SHOV A 1 A_Raise(12);
			Loop;
		Fire:
			SHOV D 1;
			TNT1 A 0 A_ReFire();
			SHOV A 1 A_PlaySound("sweapons/swordswing", 1);
			SHOV B 1;
			SHOV C 1 {
				if (CountInv("PowerSuper")) {
					A_CustomPunch(600, 0, 0, "ShadowMeleeAtk", 75, 0, 0, "ArmorBonus", "sweapons/shovelbonk");
				}
				else {
					A_CustomPunch(300, 0, 0, "ShadowMeleeAtk", 75, 0, 0, "ArmorBonus", "sweapons/shovelbonk");
				}
			}
			SHOV CCCCCCCCCBA 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			Goto Ready;
		Spawn:
			SHVL A -1;
			Stop;
	}
}

class DarkAssault : LockLoadWeapon
{
	Default
	{
		Weapon.SelectionOrder 1300;
		Weapon.AmmoUse 10;
		Weapon.AmmoGive 20;
		Weapon.KickBack 500;
		Weapon.AmmoType "ChaosEnergy";
		AttackSound "weapons/shotgf";
		Tag "Dark Assaulter";
		Inventory.PickupMessage "Dark Assaulter";
	}
	States
	{
		Ready:
			AA12 A 1 A_WeaponReady();
			Loop;
		Deselect:
			#### # 1 A_Lower(12);
			Loop;
		Select:
			AA12 A 1 A_Raise(12);
			Loop;
		Fire:
			AA12 A 2;
			AA12 A 0 A_FireBullets(6, 2, 8, 9, "BulletPuff");
			AA12 A 0 A_PlaySound("sweapons/darkshotty", CHAN_WEAPON);
			AA12 A 0 {
				if (CountInv("PowerSuper")) { A_GunFlash("SuperFlash"); } 
				else { A_GunFlash(); }
			}
			AA12 A 3 { if (CountInv("PowerSuper")) { A_ReFire(); } }
			AA12 B 2;
			Goto Ready;
		Flash:
			AAFL A 2 Bright A_Light1;
			Goto LightDone;
		SuperFlash:
			AAFL A 1 Bright A_Light1;
			Goto LightDone;
		Spawn:
			SHOT A -1;
			Stop;
	}
}

class ChaosEmerald : LockLoadWeapon
{
	Default
	{
		Weapon.SelectionOrder 3700;
		Weapon.AmmoType "ChaosEnergy";
		Weapon.AmmoUse 400;
		Inventory.PickupMessage "Chaos Emerald";
		Tag "Chaos Emerald";
		+WEAPON.AMMO_OPTIONAL
	}
	States
	{
		Ready:
			CARM A 1 A_WeaponReady();
			TNT1 A 0
			{
				if (!CountInv("Damn4thChaos")) {
					A_GiveInventory("Damn4thChaos");
					ACS_NamedExecute("Damn4thChaosEmerald");
					ACS_NamedExecute("Subtitles", 0, 17);
				}
				if (!CountInv("PowerSuper") && !CountInv("Charging") && CountInv("ChaosEnergy") < 401) {
					A_GiveInventory("ChaosEnergy", 1);
					if (CountInv("ChaosEnergy") > 400) { A_SetInventory("ChaosEnergy", 400); }
				}
			}
			Loop;
		Deselect:
			#### # 1 A_Lower(12);
			Loop;
		Select:
			CARM A 1 A_Lower(12);
			Loop;
		Fire:
			TNT1 A 0 A_JumpIf(CountInv("PowerSuper"), "AFire");
			TNT1 A 0 A_JumpIf(CountInv("ChaosEnergy") < 400, "Error");
			TNT1 A 0 A_JumpIf(CountInv("ChaosEnergy") >= 400, "AFire");
			Goto Ready;
		AFire:
			TNT1 A 0 A_PlaySound("shadow/cgrunt", 2);
			CARM A 1 {
				if (CountInv("PowerSuper")) { A_FireProjectile("SuperChaosEnergyBall", 0, false); }
				else { A_FireProjectile("SuperChaosEnergyBall", 0, true); }
			}
			CARM BCDEEEEEEEEEEEDCB 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			TNT1 A 0 A_ReFire();
			Goto Ready;
		AltFire:
			TNT1 A 0 A_JumpIf(CountInv("ChaosEnergy") > 15, "RingCheck");
			TNT1 A 0 A_JumpIf(CountInv("ChaosEnergy") < 1, "Error");
			Goto Ready;
		RingCheck:
			TNT1 A 0 A_JumpIf(Health > 299, "Error");
			TNT1 A 0 A_JumpIf(Health < 299, "ChaosCharge");
			Goto Ready;
		Error:
			TNT1 A 0 A_TakeInventory("Charging");
			TNT1 A 0 A_PlaySound("shadow/error", 4096);
			Goto Ready;
		ChaosCharge:
			TNT1 A 0 A_GiveInventory("Charging");
			TNT1 A 0 A_PlaySound("sweapons/healthcharge", 4096);
			CARM F 1 A_TakeInventory("ChaosEnergy", 5);
			TNT1 A 0 A_GiveInventory("Health", 15);
			TNT1 A 0 { if (Health > 300) { A_SetHealth(300); } }
			TNT1 A 0 A_ReFire("AltFire");
			TNT1 A 0 A_TakeInventory("Charging");
			Goto Ready;
		Spawn:
			CHSM G -1;
			Stop;
	}
}

class ShadowKnife : LockLoadWeapon
{
	int hasKnife;
	Default
	{
		Weapon.SelectionOrder 3800;
		Weapon.KickBack 0;
		Inventory.PickupMessage "Troll Slaiying Knife";
		Tag "Troll Slaiying Knife";
		+WEAPON.MELEEWEAPON
		+WEAPON.NOALERT
	}
	States
	{
		Ready:
			TNT1 A 0
			{
				if (invoker.hasKnife != 1) {
					invoker.hasKnife = 1;
					A_StartSound("theycant/trollyouif", 9);
					ACS_NamedExecute("Subtitles", 0, 16);
				}
			}
			KNIF A 1 A_WeaponReady;
			Loop;
		Deselect:
			#### # 1 A_Lower(12);
			Loop;
		Select:
			KNIF A 1 A_Raise(12);
			Loop;
		Fire:
			KNIF BBCCDDD 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			KNIF E 6 A_CustomPunch(6900, true, 0, "ShadowMeleeAtk", 64, 0, 0, "ArmorBonus", "sonicdoom/finalhit");
			KNIF CCBBBBB 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			TNT1 A 0 A_ReFire();
			Goto Ready;
		Spawn:
			SLAI Y -1;
			Stop;
	}
}

class QuadShotty : LockLoadWeapon
{
	Default
	{
		Weapon.SelectionOrder 400;
		Weapon.AmmoUse 40;
		Weapon.AmmoGive 160;
		Weapon.AmmoType "ChaosEnergy";
		Inventory.PickupMessage "Quarternary Decimator";
		Tag "Quarternary Decimator";
	}
	States
	{
		Ready:
			SHT4 A 1 A_WeaponReady();
			Loop;
		Deselect:
			#### # 1 A_Lower(12);
			Loop;
		Select:
			SHT4 A 1 A_Raise(12);
			Loop;
		Fire:
			SHT4 A 3
			{
				A_FireBullets(12, 9, 60, 6, "BulletPuff");
				A_FireBullets(6, 3, 30, 4, "BulletPuff");
				A_FireBullets(3, 1, 15, 2, "BulletPuff");
				A_PlaySound("weapons/sshotf", CHAN_WEAPON);
				A_ChangeVelocity(Cos(Pitch) * -30, 0, Sin(Pitch) * 5, CVF_Relative);
			}
			SHT4 B 9 {
				A_GunFlash();
				A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			}
			TNT1 A 0 { if (CountInv("PowerSuper")) { A_ReFire(); } }
			SHT4 BBBBBBBBBBBBBBBBBBBBBBB 1;
			SHT4 A 4 A_PlaySound("weapons/sshotl");
			SHT4 C 10 A_PlaySound("weapons/sshotc");
			TNT1 A 0 A_ReFire();
			Goto Ready;
		Flash:
			SH4F A 4 Bright A_Light1;
			Goto LightDone;
		Spawn:
			SGN2 A -1;
			Stop;
	}
}

Class DualRockets : LockLoadWeapon
{
	Default
	{
		Weapon.AmmoType "ChaosEnergy";
		Weapon.AmmoUse 32;
		Weapon.AmmoGive 128;
		Inventory.PickupMessage "Dual Assimilator";
		Tag "Dual Assimilator";
		+Weapon.Explosive
		+Weapon.NoAutoFire
	}
	States
	{
		Ready:
			DGLG A 1 A_WeaponReady();
			Loop;
		Deselect:
			#### # 1 A_Lower(12);
			Loop;
		Select:
			DGLG A 1 A_Raise(12);
			Loop;
		Fire:
			DGLG A 3;
			DGLG B 7 Bright
			{
				if (CountInv("PowerSuper")) {
					A_FireProjectile("DuellingRocket", -3, 0,  3);
					A_FireProjectile("DuellingRocket", 3, 0, -3);
					A_FireProjectile("DuellingRocket", -5, 0,  5);
					A_FireProjectile("DuellingRocket", 5, 0, -5);
				} else {
					A_FireProjectile("DuellingRocket", -3, 1,  3);
					A_FireProjectile("DuellingRocket", 3, 1, -3);
				}
			}
			DGLG AAAAAAAAAAAAAAA 1 A_WeaponReady(WRF_NOBOB|WRF_NOFIRE);
			Goto Ready;
		Spawn:
			DOUG A -1;
			Stop;
	}
}